name: "Test runner"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.os.fullname }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        os:
            - { prettyname: Windows, fullname: windows-latest }
            - { prettyname: macOS, fullname: macos-latest }
            - { prettyname: Linux, fullname: ubuntu-latest }

    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build -c Debug McServersScanner.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal McServersScanner.sln